spring.application.name=car-seller
spring.datasource.url=jdbc:postgresql://localhost:5432/car_seller
spring.datasource.username=postgres
spring.datasource.password=postgres

ollama.base-url=http://localhost:11434